# Code generated by bitproto. DO NOT EDIT.


import json
from dataclasses import dataclass, field
from typing import ClassVar, Dict, List, Union
from enum import IntEnum, unique

from bitprotolib import bp


# Timestamp in milliseconds (uint32 covers ~49 days at 1ms resolution)
Timestamp = int # 32bit

def bp_processor_Timestamp() -> bp.Processor:
    return bp.AliasProcessor(bp.Uint(32))

def bp_default_factory_Timestamp() -> Timestamp:
    return 0


# Scaled position: millimeters from origin (range ±32.767 m)
PositionScaled = int # 16bit

def bp_processor_PositionScaled() -> bp.Processor:
    return bp.AliasProcessor(bp.Int(16))

def bp_default_factory_PositionScaled() -> PositionScaled:
    return 0


# Scaled angle: 0.01 degree per unit (range ±327.67°)
AngleScaled = int # 16bit

def bp_processor_AngleScaled() -> bp.Processor:
    return bp.AliasProcessor(bp.Int(16))

def bp_default_factory_AngleScaled() -> AngleScaled:
    return 0


# Scaled linear velocity: 1 mm/s per unit (range ±32.767 m/s)
LinearVelocityScaled = int # 16bit

def bp_processor_LinearVelocityScaled() -> bp.Processor:
    return bp.AliasProcessor(bp.Int(16))

def bp_default_factory_LinearVelocityScaled() -> LinearVelocityScaled:
    return 0


# Scaled angular velocity: 0.01 rad/s per unit (range ±327.67 rad/s)
AngularVelocityScaled = int # 16bit

def bp_processor_AngularVelocityScaled() -> bp.Processor:
    return bp.AliasProcessor(bp.Int(16))

def bp_default_factory_AngularVelocityScaled() -> AngularVelocityScaled:
    return 0


# Maximum valid robot ID (11 robots: IDs 0–10)
ROBOT_ID_MAX: int = 10


# Broadcast address — all robots execute, none reply
ROBOT_ID_BROADCAST: int = 15


# Motion command from base station to a specific robot or broadcast
MSG_TYPE_COMMAND: int = 0


# Configuration command (set ID, run calibration, etc.)
MSG_TYPE_CONFIG: int = 1


# Telemetry response from robot back to base station
MSG_TYPE_TELEMETRY: int = 2


# Assign a new robot ID (new ID provided in robot_id field of RobotConfig)
CONFIG_FLAG_SET_ID: int = 1


# Trigger the wheel encoder calibration routine on the robot
CONFIG_FLAG_RUN_CALIBRATION: int = 2


# Trigger magnetometer calibration only
CONFIG_FLAG_CALIBRATE_MAG: int = 4


# Reset all NVS-stored configuration to factory defaults
CONFIG_FLAG_RESET_NVS: int = 8


# Full NVS erase — all namespaces, all keys
CONFIG_FLAG_FACTORY_RESET: int = 16


# Bit 0:  Communication loss with base station
ERROR_COMM_LOSS: int = 1


# Bit 1:  IMU failure
ERROR_IMU_FAIL: int = 2


# Bit 2:  TOF sensor failure
ERROR_TOF_FAIL: int = 4


# Bit 3:  Battery undervoltage
ERROR_BATT_UNDERVOLT: int = 8


# Bit 4:  Battery overvoltage
ERROR_BATT_OVERVOLT: int = 16


# Bit 5:  Kicker capacitor not charging
ERROR_KICKER_NO_CHARGE: int = 32


# Bit 6:  Encoder reading invalid (any encoder)
ERROR_ENCODER_INVALID: int = 64


# Bit 7:  Temperature warning
ERROR_TEMPERATURE_WARN: int = 128


# Bit 8:  Motor 0 fault
ERROR_MOTOR0_FAULT: int = 256


# Bit 9:  Motor 1 fault
ERROR_MOTOR1_FAULT: int = 512


# Bit 10: Motor 2 fault
ERROR_MOTOR2_FAULT: int = 1024


# Bit 11: Motor 3 fault
ERROR_MOTOR3_FAULT: int = 2048


@dataclass
class Header(bp.MessageBase):
    """
    ---------------------------------------------------------------------------
    Header message, defines the msg type, robot ID and timestamp
    ---------------------------------------------------------------------------
    """
    # Number of bytes to serialize class Header
    BYTES_LENGTH: ClassVar[int] = 5

    msg_type: int = 0 # 4bit
    # Message type (e.g. MSG_TYPE_COMMAND)
    robot_id: int = 0 # 4bit
    # Target robot ID or ROBOT_ID_BROADCAST
    timestamp: Timestamp = field(default_factory=bp_default_factory_Timestamp) # 32bit

    def __post_init__(self):
        pass

    @staticmethod
    def dict_factory(kv_pairs):
        return {k: v for k, v in kv_pairs if not k.startswith('_enum_field_proxy__')}

    def bp_processor(self) -> bp.Processor:
        field_processors: List[bp.Processor] = [
            bp.MessageFieldProcessor(1, bp.Uint(4)),
            bp.MessageFieldProcessor(2, bp.Uint(4)),
            bp.MessageFieldProcessor(3, bp_processor_Timestamp()),
        ]
        return bp.MessageProcessor(False, 40, field_processors)

    def bp_set_byte(self, di: bp.DataIndexer, lshift: int, b: bp.byte) -> None:
        if di.field_number == 1:
            self.msg_type |= (int(b) << lshift)
        if di.field_number == 2:
            self.robot_id |= (int(b) << lshift)
        if di.field_number == 3:
            self.timestamp |= (int(b) << lshift)
        return

    def bp_get_byte(self, di: bp.DataIndexer, rshift: int) -> bp.byte:
        if di.field_number == 1:
            return (self.msg_type >> rshift) & 255
        if di.field_number == 2:
            return (self.robot_id >> rshift) & 255
        if di.field_number == 3:
            return (self.timestamp >> rshift) & 255
        return bp.byte(0)  # Won't reached

    def bp_get_accessor(self, di: bp.DataIndexer) -> bp.Accessor:
        return bp.NilAccessor() # Won't reached

    def encode(self) -> bytearray:
        """
        Encode this object to bytearray.
        """
        s = bytearray(self.BYTES_LENGTH)
        ctx = bp.ProcessContext(True, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)
        return ctx.s

    def decode(self, s: bytearray) -> None:
        """
        Decode given bytearray s to this object.
        :param s: A bytearray with length at least `BYTES_LENGTH`.
        """
        assert len(s) >= self.BYTES_LENGTH, bp.NotEnoughBytes()
        ctx = bp.ProcessContext(False, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)

    def bp_process_int(self, di: bp.DataIndexer) -> None:
        return


@dataclass
class Pose(bp.MessageBase):
    # Number of bytes to serialize class Pose
    BYTES_LENGTH: ClassVar[int] = 12

    x: PositionScaled = field(default_factory=bp_default_factory_PositionScaled) # 16bit
    # X coordinate (mm)
    y: PositionScaled = field(default_factory=bp_default_factory_PositionScaled) # 16bit
    # Y coordinate (mm)
    angle: AngleScaled = field(default_factory=bp_default_factory_AngleScaled) # 16bit
    # Orientation (0.01°)
    x_v: LinearVelocityScaled = field(default_factory=bp_default_factory_LinearVelocityScaled) # 16bit
    # Linear velocity in X (mm/s)
    y_v: LinearVelocityScaled = field(default_factory=bp_default_factory_LinearVelocityScaled) # 16bit
    # Linear velocity in Y (mm/s)
    angular_vel: AngularVelocityScaled = field(default_factory=bp_default_factory_AngularVelocityScaled) # 16bit

    def __post_init__(self):
        pass

    @staticmethod
    def dict_factory(kv_pairs):
        return {k: v for k, v in kv_pairs if not k.startswith('_enum_field_proxy__')}

    def bp_processor(self) -> bp.Processor:
        field_processors: List[bp.Processor] = [
            bp.MessageFieldProcessor(1, bp_processor_PositionScaled()),
            bp.MessageFieldProcessor(2, bp_processor_PositionScaled()),
            bp.MessageFieldProcessor(3, bp_processor_AngleScaled()),
            bp.MessageFieldProcessor(4, bp_processor_LinearVelocityScaled()),
            bp.MessageFieldProcessor(5, bp_processor_LinearVelocityScaled()),
            bp.MessageFieldProcessor(6, bp_processor_AngularVelocityScaled()),
        ]
        return bp.MessageProcessor(False, 96, field_processors)

    def bp_set_byte(self, di: bp.DataIndexer, lshift: int, b: bp.byte) -> None:
        if di.field_number == 1:
            self.x |= bp.int16((int(b) << lshift))
        if di.field_number == 2:
            self.y |= bp.int16((int(b) << lshift))
        if di.field_number == 3:
            self.angle |= bp.int16((int(b) << lshift))
        if di.field_number == 4:
            self.x_v |= bp.int16((int(b) << lshift))
        if di.field_number == 5:
            self.y_v |= bp.int16((int(b) << lshift))
        if di.field_number == 6:
            self.angular_vel |= bp.int16((int(b) << lshift))
        return

    def bp_get_byte(self, di: bp.DataIndexer, rshift: int) -> bp.byte:
        if di.field_number == 1:
            return (self.x >> rshift) & 255
        if di.field_number == 2:
            return (self.y >> rshift) & 255
        if di.field_number == 3:
            return (self.angle >> rshift) & 255
        if di.field_number == 4:
            return (self.x_v >> rshift) & 255
        if di.field_number == 5:
            return (self.y_v >> rshift) & 255
        if di.field_number == 6:
            return (self.angular_vel >> rshift) & 255
        return bp.byte(0)  # Won't reached

    def bp_get_accessor(self, di: bp.DataIndexer) -> bp.Accessor:
        return bp.NilAccessor() # Won't reached

    def encode(self) -> bytearray:
        """
        Encode this object to bytearray.
        """
        s = bytearray(self.BYTES_LENGTH)
        ctx = bp.ProcessContext(True, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)
        return ctx.s

    def decode(self, s: bytearray) -> None:
        """
        Decode given bytearray s to this object.
        :param s: A bytearray with length at least `BYTES_LENGTH`.
        """
        assert len(s) >= self.BYTES_LENGTH, bp.NotEnoughBytes()
        ctx = bp.ProcessContext(False, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)

    def bp_process_int(self, di: bp.DataIndexer) -> None:
        return


@dataclass
class RobotCommand(bp.MessageBase):
    """
    ---------------------------------------------------------------------------
    RobotCommand — base station → robot (unicast or broadcast)
    First byte is msg_type; robot peeks it to demux before full decode.
    Broadcast (robot_id == ROBOT_ID_BROADCAST): execute, do NOT reply.
    Unicast: execute and reply with RobotTelemetry.
    
    Size: 5 (Header) + 12 (target_pose) + 12 (vision_pose) + 1 (kick_velocity) = 30 bytes  ✓
    ---------------------------------------------------------------------------
    """
    # Number of bytes to serialize class RobotCommand
    BYTES_LENGTH: ClassVar[int] = 30

    header: Header = field(default_factory=Header) # 40bit
    # Message header (msg_type, robot_id, timestamp)
    target_pose: Pose = field(default_factory=Pose) # 96bit
    # Desired pose / velocity setpoint
    vision_pose: Pose = field(default_factory=Pose) # 96bit
    # Current pose from vision system
    kick_velocity: int = 0 # 8bit

    def __post_init__(self):
        pass

    @staticmethod
    def dict_factory(kv_pairs):
        return {k: v for k, v in kv_pairs if not k.startswith('_enum_field_proxy__')}

    def bp_processor(self) -> bp.Processor:
        field_processors: List[bp.Processor] = [
            bp.MessageFieldProcessor(1, Header().bp_processor()),
            bp.MessageFieldProcessor(2, Pose().bp_processor()),
            bp.MessageFieldProcessor(3, Pose().bp_processor()),
            bp.MessageFieldProcessor(4, bp.Uint(8)),
        ]
        return bp.MessageProcessor(False, 240, field_processors)

    def bp_set_byte(self, di: bp.DataIndexer, lshift: int, b: bp.byte) -> None:
        if di.field_number == 4:
            self.kick_velocity |= (int(b) << lshift)
        return

    def bp_get_byte(self, di: bp.DataIndexer, rshift: int) -> bp.byte:
        if di.field_number == 4:
            return (self.kick_velocity >> rshift) & 255
        return bp.byte(0)  # Won't reached

    def bp_get_accessor(self, di: bp.DataIndexer) -> bp.Accessor:
        if di.field_number == 1:
            return self.header
        if di.field_number == 2:
            return self.target_pose
        if di.field_number == 3:
            return self.vision_pose
        return bp.NilAccessor() # Won't reached

    def encode(self) -> bytearray:
        """
        Encode this object to bytearray.
        """
        s = bytearray(self.BYTES_LENGTH)
        ctx = bp.ProcessContext(True, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)
        return ctx.s

    def decode(self, s: bytearray) -> None:
        """
        Decode given bytearray s to this object.
        :param s: A bytearray with length at least `BYTES_LENGTH`.
        """
        assert len(s) >= self.BYTES_LENGTH, bp.NotEnoughBytes()
        ctx = bp.ProcessContext(False, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)

    def bp_process_int(self, di: bp.DataIndexer) -> None:
        return


@dataclass
class RobotConfig(bp.MessageBase):
    """
    ---------------------------------------------------------------------------
    RobotConfig — base station → robot (always unicast; no reply expected)
    Use config_flags bitmask to select operation(s); param carries auxiliary value.
    
    Size: 5 (Header) + 1 (config_flags) + 2 (param) = 8 bytes  ✓
    ---------------------------------------------------------------------------
    """
    # Number of bytes to serialize class RobotConfig
    BYTES_LENGTH: ClassVar[int] = 8

    header: Header = field(default_factory=Header) # 40bit
    # Message header (msg_type, robot_id, timestamp)
    config_flags: int = 0 # 8bit
    # Bitmask of CONFIG_FLAG_* constants
    param: int = 0 # 16bit

    def __post_init__(self):
        pass

    @staticmethod
    def dict_factory(kv_pairs):
        return {k: v for k, v in kv_pairs if not k.startswith('_enum_field_proxy__')}

    def bp_processor(self) -> bp.Processor:
        field_processors: List[bp.Processor] = [
            bp.MessageFieldProcessor(1, Header().bp_processor()),
            bp.MessageFieldProcessor(2, bp.Uint(8)),
            bp.MessageFieldProcessor(3, bp.Uint(16)),
        ]
        return bp.MessageProcessor(False, 64, field_processors)

    def bp_set_byte(self, di: bp.DataIndexer, lshift: int, b: bp.byte) -> None:
        if di.field_number == 2:
            self.config_flags |= (int(b) << lshift)
        if di.field_number == 3:
            self.param |= (int(b) << lshift)
        return

    def bp_get_byte(self, di: bp.DataIndexer, rshift: int) -> bp.byte:
        if di.field_number == 2:
            return (self.config_flags >> rshift) & 255
        if di.field_number == 3:
            return (self.param >> rshift) & 255
        return bp.byte(0)  # Won't reached

    def bp_get_accessor(self, di: bp.DataIndexer) -> bp.Accessor:
        if di.field_number == 1:
            return self.header
        return bp.NilAccessor() # Won't reached

    def encode(self) -> bytearray:
        """
        Encode this object to bytearray.
        """
        s = bytearray(self.BYTES_LENGTH)
        ctx = bp.ProcessContext(True, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)
        return ctx.s

    def decode(self, s: bytearray) -> None:
        """
        Decode given bytearray s to this object.
        :param s: A bytearray with length at least `BYTES_LENGTH`.
        """
        assert len(s) >= self.BYTES_LENGTH, bp.NotEnoughBytes()
        ctx = bp.ProcessContext(False, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)

    def bp_process_int(self, di: bp.DataIndexer) -> None:
        return


@dataclass
class RobotTelemetry(bp.MessageBase):
    """
    ---------------------------------------------------------------------------
    RobotTelemetry — robot → base station (reply to unicast RobotCommand only)
    
    Size: 5 (Header) + 12 (robot_pose) + 1 (battery_percentage) + 2 (kicker_voltage) + 2 (error_flags) = 22 bytes  ✓
    ---------------------------------------------------------------------------
    """
    # Number of bytes to serialize class RobotTelemetry
    BYTES_LENGTH: ClassVar[int] = 22

    header: Header = field(default_factory=Header) # 40bit
    # Message header (msg_type, robot_id, timestamp)
    robot_pose: Pose = field(default_factory=Pose) # 96bit
    # Current estimated pose
    battery_percentage: int = 0 # 8bit
    # 0–100 %
    kicker_voltage: int = 0 # 16bit
    # Voltage in 0.01 V units (e.g. 1650 = 16.50 V)
    error_flags: int = 0 # 16bit

    def __post_init__(self):
        pass

    @staticmethod
    def dict_factory(kv_pairs):
        return {k: v for k, v in kv_pairs if not k.startswith('_enum_field_proxy__')}

    def bp_processor(self) -> bp.Processor:
        field_processors: List[bp.Processor] = [
            bp.MessageFieldProcessor(1, Header().bp_processor()),
            bp.MessageFieldProcessor(2, Pose().bp_processor()),
            bp.MessageFieldProcessor(3, bp.Uint(8)),
            bp.MessageFieldProcessor(4, bp.Uint(16)),
            bp.MessageFieldProcessor(5, bp.Uint(16)),
        ]
        return bp.MessageProcessor(False, 176, field_processors)

    def bp_set_byte(self, di: bp.DataIndexer, lshift: int, b: bp.byte) -> None:
        if di.field_number == 3:
            self.battery_percentage |= (int(b) << lshift)
        if di.field_number == 4:
            self.kicker_voltage |= (int(b) << lshift)
        if di.field_number == 5:
            self.error_flags |= (int(b) << lshift)
        return

    def bp_get_byte(self, di: bp.DataIndexer, rshift: int) -> bp.byte:
        if di.field_number == 3:
            return (self.battery_percentage >> rshift) & 255
        if di.field_number == 4:
            return (self.kicker_voltage >> rshift) & 255
        if di.field_number == 5:
            return (self.error_flags >> rshift) & 255
        return bp.byte(0)  # Won't reached

    def bp_get_accessor(self, di: bp.DataIndexer) -> bp.Accessor:
        if di.field_number == 1:
            return self.header
        if di.field_number == 2:
            return self.robot_pose
        return bp.NilAccessor() # Won't reached

    def encode(self) -> bytearray:
        """
        Encode this object to bytearray.
        """
        s = bytearray(self.BYTES_LENGTH)
        ctx = bp.ProcessContext(True, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)
        return ctx.s

    def decode(self, s: bytearray) -> None:
        """
        Decode given bytearray s to this object.
        :param s: A bytearray with length at least `BYTES_LENGTH`.
        """
        assert len(s) >= self.BYTES_LENGTH, bp.NotEnoughBytes()
        ctx = bp.ProcessContext(False, s)
        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)

    def bp_process_int(self, di: bp.DataIndexer) -> None:
        return